# примеры API-запросов

@port = 7000
@baseUrl = http://localhost:{{port}}
@token = 3ea487c3-84c4-4854-bea3-6f9d39eaaaf5

# получение пользователей
GET {{baseUrl}}/users

###

# получение истории чата (для теста)
GET {{baseUrl}}/chat

###

# добавление пользователя
POST {{baseUrl}}/check-nickname/?nickname=asd

###

# добавление пользователя
POST {{baseUrl}}/check-nickname/?nickname=123

###
# удаление пользователя
DELETE {{baseUrl}}/check-nickname/asd

###

# удаление пользователя
DELETE {{baseUrl}}/check-nickname/asd
Content-Type: application/json
Authorization: Token 4ffff8d9-89b1-4ee9-aa71-eb5ad3aad649

###